apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secretclaim-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: controller-manager    
  namespace: default
- kind: ServiceAccount
  name: api-server-sa          
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secretclaim-manager
