apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secretclaim-manager
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["secrets.myapp.io"]  
  resources: ["secretclaims"]
  verbs: ["get","list","watch","create","update","patch","delete"]
