apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: k8s-secret-manager
    app.kubernetes.io/managed-by: kustomize
  name: k8s-secret-manager-controller-manager
  namespace: k8s-secret-manager-system