apiVersion: secrets.myapp.io/v1alpha1
kind: SecretClaim
metadata:
  labels:
    app.kubernetes.io/name: k8s-secret-manager
    app.kubernetes.io/managed-by: kustomize
  name: secretclaim-sample
spec:
  # TODO(user): Add fields here
