apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-secret-manager-leader-election-binding
subjects:
- kind: ServiceAccount
  name: k8s-secret-manager-controller-manager
  namespace: k8s-secret-manager-system
roleRef:
  kind: ClusterRole
  name: k8s-secret-manager-leader-election-role
  apiGroup: rbac.authorization.k8s.io
